import Head from 'next/head'
import { AudioRecorder, useAudioRecorder } from 'react-audio-voice-recorder'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import { blob } from 'stream/consumers'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const recordingControls = useAudioRecorder()
  const [recording, setRecording] = useState(false)

  const sendToServer = async (blob: Blob) => {
    const respon = await fetch("http://localhost:3001/", {
      method: "POST",
      body: blob
    })
    const json = await respon.json()
    alert(json.msg)
  }

  return (
    <>
      <Head>
        <title>snakra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={async () => {
          const resp = await fetch("http://localhost:3001/")
          const json = await resp.json()
          console.log(json.msg)
        }}>test go server</button>
        <AudioRecorder onRecordingComplete={(blob) => sendToServer(blob)} recorderControls={recordingControls} />
      </main>
    </>
  )
}
