import Head from 'next/head'
import { AudioRecorder, useAudioRecorder } from 'react-audio-voice-recorder'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  const recordingControls = useAudioRecorder()
  const { isRecording } = recordingControls
  const [recording, setRecording] = useState(false)
  const [countdown, setCountdown] = useState(15)
  const [id, setId] = useState<string | null>(null)

  useEffect(() => {
    if (isRecording) {
        const interval = setInterval(() => setCountdown(countdown - 1), 1000)
        return () => clearInterval(interval)
      }
    }, [isRecording, countdown])

  useEffect(() => {
    if (id) {
      router.replace(`${id}`)
    }
  }, [id, router])

  useEffect(() => {
    if (countdown !== 0) {
        return
      }
    const { stopRecording ,recordingBlob } = recordingControls
    stopRecording()
    if (recordingBlob) onRecordingComplete(recordingBlob)
    }, [countdown])

  const onRecordingComplete = async (blob: Blob) => {
    if (blob) convertToBase64String(blob)
    }

  const convertToBase64String = (blob: Blob) => {
    const reader = new FileReader()
    var base64data
    reader.readAsDataURL(blob)
    reader.onloadend = async () => {
      base64data = reader.result
      const respon = await fetch("http://localhost:8080/api", {
        method: "POST",
        body: base64data
      })
      const { id } = await respon.json()
      setId(id)
    }
  }

  return (
    <>
      <Head>
        <title>snakra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AudioRecorder onRecordingComplete={(blob) => onRecordingComplete(blob)}
          recorderControls={recordingControls} />
      </main>
    </>
  )
}
