version: "3.8"
services:
  snakra-pgdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: kesh
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
